// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrivateInvestigationTechnology.Datos;

#nullable disable

namespace PrivateInvestigationTechnology.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240908022042_PTC_DB")]
    partial class PTC_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__ADMINIST__2D89616FD06B269C");

                    b.ToTable("Administrador");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionActividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DetallesAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaActividad")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("HoraActividad")
                        .HasColumnType("datetime");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__AUDITORI__2C0A46DB57C0C4C3");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_AUDITORIA_ID_Usuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Antecedentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CadenaCustodia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstudiosSeguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdDetective")
                        .HasColumnType("int");

                    b.Property<string>("InvestigacionExtorsion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigacionInfidelidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvestigacionRobosEmpresariales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecuperacionVehiculos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__CASOS__8D2EE0F8198FF510");

                    b.HasIndex(new[] { "IdCliente" }, "IX_CASOS_ID_Cliente");

                    b.HasIndex(new[] { "IdDetective" }, "IX_CASOS_ID_Detective");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id")
                        .HasName("PK__CLIENTE__E005FBFFD9D25160");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Clausulas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaCierre")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdDetective")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__CONTRATO__B16B9C193079E2D4");

                    b.HasIndex(new[] { "IdCliente" }, "IX_CONTRATO_ID_Cliente");

                    b.HasIndex(new[] { "IdDetective" }, "IX_CONTRATO_ID_Detective");

                    b.ToTable("Contrato");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Detective", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__DETECTIV__8B0EE69682BC2615");

                    b.ToTable("Detective");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Evidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEvidencia")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCasos")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__EVIDENCI__7E4E2469BB4D9A36");

                    b.HasIndex(new[] { "IdCasos" }, "IX_EVIDENCIA_ID_Casos");

                    b.ToTable("Evidencia");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DescripcionServicio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("EstadoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPagar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Id")
                        .HasName("PK__FACTURA__E9D586A8C548166A");

                    b.HasIndex(new[] { "IdCliente" }, "IX_FACTURA_ID_Cliente");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NumeroCelular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id")
                        .HasName("PK__FORMULAR__5E51A260A355C47A");

                    b.HasIndex(new[] { "IdCliente" }, "IX_FORMULARIO_ID_Cliente");

                    b.ToTable("Formulario");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Historial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__HISTORIA__ECA894541749A391");

                    b.HasIndex(new[] { "IdCliente" }, "IX_HISTORIAL_ID_Cliente");

                    b.ToTable("Historial");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime");

                    b.Property<int?>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__PERSONA__E9916EC1AEFC8FCB");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Persona");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.RegistroCaso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EstadoRegistro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("FechaFinalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdCasos")
                        .HasColumnType("int");

                    b.Property<decimal?>("SeguimientoPorcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("Id")
                        .HasName("PK__REGISTRO__02C63DCF336C0A9B");

                    b.HasIndex(new[] { "IdCasos" }, "IX_REGISTRO_CASOS_ID_Casos");

                    b.ToTable("RegistroCasos");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.RegistroMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__REGISTRO__BD4C405AD6E7EB8F");

                    b.HasIndex(new[] { "IdAdministrador" }, "IX_REGISTRO_MANTENIMIENTO_ID_Administrador");

                    b.ToTable("RegistroMantenimiento");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__ROLES__F92302F1CF88DF30");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.TipoEvidencia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivosDigitales")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdEvidencia")
                        .HasColumnType("int");

                    b.Property<string>("TipoAudio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoFotografia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TipoVideo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__TIPO_EVI__EA1B819E989F9A41");

                    b.HasIndex(new[] { "IdEvidencia" }, "IX_TIPO_EVIDENCIA_ID_Evidencia");

                    b.ToTable("TipoEvidencia");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__USUARIO__DE4431C517669D5D");

                    b.HasIndex(new[] { "RolId" }, "IX_USUARIO_RolId");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Administrador", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Persona", "IdNavigation")
                        .WithOne("Administrador")
                        .HasForeignKey("PrivateInvestigationTechnology.Models.Administrador", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__ADMINISTR__ID_Ad__3E52440B");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Auditoria", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK__AUDITORIA__ID_Us__656C112C");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Caso", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__CASOS__ID_Client__5535A963");

                    b.HasOne("PrivateInvestigationTechnology.Models.Detective", "IdDetectiveNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdDetective")
                        .HasConstraintName("FK__CASOS__ID_Detective__5535A963");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetectiveNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Cliente", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Persona", "IdNavigation")
                        .WithOne("Cliente")
                        .HasForeignKey("PrivateInvestigationTechnology.Models.Cliente", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__CLIENTE__ID_Clie__440B1D61");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Contrato", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__CONTRATO__ID_Cli__52593CB8");

                    b.HasOne("PrivateInvestigationTechnology.Models.Detective", "IdDetectiveNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdDetective")
                        .HasConstraintName("FK__CONTRATO__ID_Detective__52593CB8");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetectiveNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Detective", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Persona", "IdNavigation")
                        .WithOne("Detective")
                        .HasForeignKey("PrivateInvestigationTechnology.Models.Detective", "Id")
                        .IsRequired()
                        .HasConstraintName("FK__DETECTIVE__ID_De__412EB0B6");

                    b.Navigation("IdNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Evidencia", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Caso", "IdCasosNavigation")
                        .WithMany("Evidencia")
                        .HasForeignKey("IdCasos")
                        .IsRequired()
                        .HasConstraintName("FK__EVIDENCIA__ID_Ca__5AEE82B9");

                    b.Navigation("IdCasosNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Factura", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__FACTURA__ID_Clie__4F7CD00D");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Formulario", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Formularios")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__FORMULARI__ID_Cl__49C3F6B7");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Historial", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Historials")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK__HISTORIAL__ID_Cl__4CA06362");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Persona", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdUsuario")
                        .HasConstraintName("FK_PERSONA_USUARIO");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.RegistroCaso", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Caso", "IdCasosNavigation")
                        .WithMany("RegistroCasos")
                        .HasForeignKey("IdCasos")
                        .IsRequired()
                        .HasConstraintName("FK__REGISTRO___ID_Ca__5812160E");

                    b.Navigation("IdCasosNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.RegistroMantenimiento", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Administrador", "IdAdministradorNavigation")
                        .WithMany("RegistroMantenimientos")
                        .HasForeignKey("IdAdministrador")
                        .IsRequired()
                        .HasConstraintName("FK__REGISTRO___ID_Ad__46E78A0C");

                    b.Navigation("IdAdministradorNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.TipoEvidencia", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Evidencia", "IdEvidenciaNavigation")
                        .WithMany("TipoEvidencia")
                        .HasForeignKey("IdEvidencia")
                        .IsRequired()
                        .HasConstraintName("FK__TIPO_EVID__ID_Ev__628FA481");

                    b.Navigation("IdEvidenciaNavigation");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Usuario", b =>
                {
                    b.HasOne("PrivateInvestigationTechnology.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__USUARIO__RolId__3B75D760");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Administrador", b =>
                {
                    b.Navigation("RegistroMantenimientos");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Caso", b =>
                {
                    b.Navigation("Evidencia");

                    b.Navigation("RegistroCasos");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Cliente", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Contratos");

                    b.Navigation("Facturas");

                    b.Navigation("Formularios");

                    b.Navigation("Historials");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Detective", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Contratos");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Evidencia", b =>
                {
                    b.Navigation("TipoEvidencia");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Persona", b =>
                {
                    b.Navigation("Administrador");

                    b.Navigation("Cliente");

                    b.Navigation("Detective");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PrivateInvestigationTechnology.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
