// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _17.PrivateInvestigationTechnology_PTC.Data;

#nullable disable

namespace _17.PrivateInvestigationTechnology_PTC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240926003106_PTC_DB")]
    partial class PTC_DB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Administrador", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Administ__3214EC07DD24900F");

                    b.ToTable("Administrador", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Auditorium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Auditori__3214EC072E59CF31");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Auditoria");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Caso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdDetective")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Caso__3214EC0733CC1955");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDetective");

                    b.ToTable("Caso", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Cliente__3214EC075361933A");

                    b.ToTable("Cliente", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Contrato", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdDetective")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Contrato__3214EC07B43553BC");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDetective");

                    b.ToTable("Contrato", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Detective", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Detectiv__3214EC07FA53F2E0");

                    b.ToTable("Detective", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Evidencium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Evidenci__3214EC0782111570");

                    b.HasIndex("IdCaso");

                    b.ToTable("Evidencia");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Factura", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id")
                        .HasName("PK__Factura__3214EC07423EC717");

                    b.HasIndex("IdCliente");

                    b.ToTable("Factura", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Formulario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Detalles")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Formular__3214EC074C3444E2");

                    b.HasIndex("IdCliente");

                    b.ToTable("Formulario", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Historial", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Historia__3214EC075A9340F3");

                    b.HasIndex("IdCliente");

                    b.ToTable("Historial", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Persona", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("IdAdministrador")
                        .HasColumnType("int");

                    b.Property<int?>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int?>("IdDetective")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__Persona__3214EC07729008E3");

                    b.HasIndex("IdAdministrador");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdDetective");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Persona", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.RegistroCaso", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registro__3214EC07897CCA72");

                    b.HasIndex("IdCaso");

                    b.ToTable("RegistroCaso", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.RegistroMantenimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("FechaFinal")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime");

                    b.Property<int>("IdAdministrador")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Registro__3214EC070A3023DE");

                    b.HasIndex(new[] { "IdAdministrador" }, "IX_REGISTRO_MANTENIMIENTO_ID_Administrador");

                    b.ToTable("RegistroMantenimiento", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Role__3214EC07D3CA7512");

                    b.ToTable("Role", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.TipoEvidencium", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("IdEvidencia")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__TipoEvid__3214EC07B4945479");

                    b.HasIndex("IdEvidencia");

                    b.ToTable("TipoEvidencia");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Usuario__3214EC07FFA5209D");

                    b.HasIndex("RolId");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Auditorium", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Auditoria")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Auditoria_Usuario");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Caso", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Caso_Cliente");

                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Detective", "IdDetectiveNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdDetective")
                        .IsRequired()
                        .HasConstraintName("FK_Caso_Detective");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetectiveNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Contrato", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Cliente");

                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Detective", "IdDetectiveNavigation")
                        .WithMany("Contratos")
                        .HasForeignKey("IdDetective")
                        .IsRequired()
                        .HasConstraintName("FK_Contrato_Detective");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetectiveNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Evidencium", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Caso", "IdCasoNavigation")
                        .WithMany("Evidencia")
                        .HasForeignKey("IdCaso")
                        .IsRequired()
                        .HasConstraintName("FK_Evidencia_Caso");

                    b.Navigation("IdCasoNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Factura", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Facturas")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Factura_Cliente");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Formulario", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Formularios")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Formulario_Cliente");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Historial", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Historials")
                        .HasForeignKey("IdCliente")
                        .IsRequired()
                        .HasConstraintName("FK_Historial_Cliente");

                    b.Navigation("IdClienteNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Persona", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Administrador", "IdAdministradorNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdAdministrador")
                        .HasConstraintName("FK_Persona_Administrador");

                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdCliente")
                        .HasConstraintName("FK_Persona_Cliente");

                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Detective", "IdDetectiveNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdDetective")
                        .HasConstraintName("FK_Persona_Detective");

                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Usuario", "IdUsuarioNavigation")
                        .WithMany("Personas")
                        .HasForeignKey("IdUsuario")
                        .IsRequired()
                        .HasConstraintName("FK_Persona_Usuario");

                    b.Navigation("IdAdministradorNavigation");

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdDetectiveNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.RegistroCaso", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Caso", "IdCasoNavigation")
                        .WithMany("RegistroCasos")
                        .HasForeignKey("IdCaso")
                        .IsRequired()
                        .HasConstraintName("FK_RegistroCaso_Caso");

                    b.Navigation("IdCasoNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.RegistroMantenimiento", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Administrador", "IdAdministradorNavigation")
                        .WithMany("RegistroMantenimientos")
                        .HasForeignKey("IdAdministrador")
                        .IsRequired()
                        .HasConstraintName("FK_RegistroMantenimiento_Administrador");

                    b.Navigation("IdAdministradorNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.TipoEvidencium", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Evidencium", "IdEvidenciaNavigation")
                        .WithMany("TipoEvidencia")
                        .HasForeignKey("IdEvidencia")
                        .IsRequired()
                        .HasConstraintName("FK_TipoEvidencia_Evidencia");

                    b.Navigation("IdEvidenciaNavigation");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Usuario", b =>
                {
                    b.HasOne("_17.PrivateInvestigationTechnology_PTC.Models.Role", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK_Usuario_Role");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Administrador", b =>
                {
                    b.Navigation("Personas");

                    b.Navigation("RegistroMantenimientos");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Caso", b =>
                {
                    b.Navigation("Evidencia");

                    b.Navigation("RegistroCasos");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Cliente", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Contratos");

                    b.Navigation("Facturas");

                    b.Navigation("Formularios");

                    b.Navigation("Historials");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Detective", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Contratos");

                    b.Navigation("Personas");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Evidencium", b =>
                {
                    b.Navigation("TipoEvidencia");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("_17.PrivateInvestigationTechnology_PTC.Models.Usuario", b =>
                {
                    b.Navigation("Auditoria");

                    b.Navigation("Personas");
                });
#pragma warning restore 612, 618
        }
    }
}
