// <auto-generated />
using System;
using DAL.Datos;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240831065652_DB_PTC")]
    partial class DB_PTC
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DAL.Models.ADMINISTRADOR", b =>
                {
                    b.Property<int>("ID_Administrador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Administrador")
                        .HasName("PK__ADMINIST__2D89616FD06B269C");

                    b.ToTable("ADMINISTRADOR");
                });

            modelBuilder.Entity("DAL.Models.AUDITORIA", b =>
                {
                    b.Property<int>("ID_Auditoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Auditoria"));

                    b.Property<string>("Descrip_Actividad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Detalles_Adicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Actividad")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Hora_Actividad")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Usuario")
                        .HasColumnType("int");

                    b.HasKey("ID_Auditoria")
                        .HasName("PK__AUDITORI__2C0A46DB57C0C4C3");

                    b.HasIndex("ID_Usuario");

                    b.ToTable("AUDITORIA");
                });

            modelBuilder.Entity("DAL.Models.CASO", b =>
                {
                    b.Property<int>("ID_Casos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Casos"));

                    b.Property<string>("Antecedentes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cadena_Custodia")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estudios_Seguridad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Investigacion_Extorsion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Investigacion_Infidelidades")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Investigacion_Robos_Empresariales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Recuperacion_Vehiculos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID_Casos")
                        .HasName("PK__CASOS__8D2EE0F8198FF510");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("CASOS");
                });

            modelBuilder.Entity("DAL.Models.CLIENTE", b =>
                {
                    b.Property<int>("ID_Cliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ID_Cliente")
                        .HasName("PK__CLIENTE__E005FBFFD9D25160");

                    b.ToTable("CLIENTE");
                });

            modelBuilder.Entity("DAL.Models.CONTRATO", b =>
                {
                    b.Property<int>("ID_Contrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Contrato"));

                    b.Property<string>("Clausulas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descrip_Servicio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Fecha_Cierre")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Tarifa")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ID_Contrato")
                        .HasName("PK__CONTRATO__B16B9C193079E2D4");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("CONTRATO");
                });

            modelBuilder.Entity("DAL.Models.DETECTIVE", b =>
                {
                    b.Property<int>("ID_Detective")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Detective")
                        .HasName("PK__DETECTIV__8B0EE69682BC2615");

                    b.ToTable("DETECTIVE");
                });

            modelBuilder.Entity("DAL.Models.EVIDENCIA", b =>
                {
                    b.Property<int>("ID_Evidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Evidencia"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Evidencia")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Casos")
                        .HasColumnType("int");

                    b.HasKey("ID_Evidencia")
                        .HasName("PK__EVIDENCI__7E4E2469BB4D9A36");

                    b.HasIndex("ID_Casos");

                    b.ToTable("EVIDENCIA");
                });

            modelBuilder.Entity("DAL.Models.FACTURA", b =>
                {
                    b.Property<int>("ID_Factura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Factura"));

                    b.Property<string>("Descripcion_Serv")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado_Pago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("Fecha_Emision")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<decimal>("Total_Pagar")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("ID_Factura")
                        .HasName("PK__FACTURA__E9D586A8C548166A");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("FACTURA");
                });

            modelBuilder.Entity("DAL.Models.FORMULARIO", b =>
                {
                    b.Property<int>("ID_Formulario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Formulario"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha_Envio")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Numero_Celular")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("ID_Formulario")
                        .HasName("PK__FORMULAR__5E51A260A355C47A");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("FORMULARIO");
                });

            modelBuilder.Entity("DAL.Models.HISTORIAL", b =>
                {
                    b.Property<int>("ID_Historial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Historial"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Fecha_Final_Histo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio_Histo")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Cliente")
                        .HasColumnType("int");

                    b.HasKey("ID_Historial")
                        .HasName("PK__HISTORIA__ECA894541749A391");

                    b.HasIndex("ID_Cliente");

                    b.ToTable("HISTORIAL");
                });

            modelBuilder.Entity("DAL.Models.PERSONA", b =>
                {
                    b.Property<int>("ID_Persona")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Persona"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("Fecha_Nacimiento")
                        .HasColumnType("datetime");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID_Persona")
                        .HasName("PK__PERSONA__E9916EC1AEFC8FCB");

                    b.ToTable("PERSONA");
                });

            modelBuilder.Entity("DAL.Models.REGISTRO_CASO", b =>
                {
                    b.Property<int>("ID_Registro_Casos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Registro_Casos"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado_Registro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Fecha_Finalizacion")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Casos")
                        .HasColumnType("int");

                    b.Property<decimal?>("Seguimiento_Porcentaje")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ID_Registro_Casos")
                        .HasName("PK__REGISTRO__02C63DCF336C0A9B");

                    b.HasIndex("ID_Casos");

                    b.ToTable("REGISTRO_CASOS");
                });

            modelBuilder.Entity("DAL.Models.REGISTRO_MANTENIMIENTO", b =>
                {
                    b.Property<int>("ID_Mantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Mantenimiento"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("Fecha_Final")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fecha_Inicio")
                        .HasColumnType("datetime");

                    b.Property<int>("ID_Administrador")
                        .HasColumnType("int");

                    b.HasKey("ID_Mantenimiento")
                        .HasName("PK__REGISTRO__BD4C405AD6E7EB8F");

                    b.HasIndex("ID_Administrador");

                    b.ToTable("REGISTRO_MANTENIMIENTO");
                });

            modelBuilder.Entity("DAL.Models.ROLE", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"));

                    b.Property<bool>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RolId")
                        .HasName("PK__ROLES__F92302F1CF88DF30");

                    b.ToTable("ROLES");
                });

            modelBuilder.Entity("DAL.Models.TIPO_EVIDENCIA", b =>
                {
                    b.Property<int>("ID_Tipo_Evidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Tipo_Evidencia"));

                    b.Property<string>("Archivos_Digitales")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("ID_Evidencia")
                        .HasColumnType("int");

                    b.Property<string>("Tipo_Audio")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo_Documento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo_Fotografia")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Tipo_Video")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Tipo_Evidencia")
                        .HasName("PK__TIPO_EVI__EA1B819E989F9A41");

                    b.HasIndex("ID_Evidencia");

                    b.ToTable("TIPO_EVIDENCIA");
                });

            modelBuilder.Entity("DAL.Models.USUARIO", b =>
                {
                    b.Property<int>("ID_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID_Usuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ID_Usuario")
                        .HasName("PK__USUARIO__DE4431C517669D5D");

                    b.HasIndex("RolId");

                    b.ToTable("USUARIO");
                });

            modelBuilder.Entity("DAL.Models.ADMINISTRADOR", b =>
                {
                    b.HasOne("DAL.Models.PERSONA", "Persona")
                        .WithOne("ADMINISTRADOR")
                        .HasForeignKey("DAL.Models.ADMINISTRADOR", "ID_Administrador")
                        .IsRequired()
                        .HasConstraintName("FK__ADMINISTR__ID_Ad__3E52440B");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DAL.Models.AUDITORIA", b =>
                {
                    b.HasOne("DAL.Models.USUARIO", "ID_UsuarioNavigation")
                        .WithMany("AUDITORIAS")
                        .HasForeignKey("ID_Usuario")
                        .IsRequired()
                        .HasConstraintName("FK__AUDITORIA__ID_Us__656C112C");

                    b.Navigation("ID_UsuarioNavigation");
                });

            modelBuilder.Entity("DAL.Models.CASO", b =>
                {
                    b.HasOne("DAL.Models.CLIENTE", "ID_ClienteNavigation")
                        .WithMany("CASOS")
                        .HasForeignKey("ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__CASOS__ID_Client__5535A963");

                    b.Navigation("ID_ClienteNavigation");
                });

            modelBuilder.Entity("DAL.Models.CLIENTE", b =>
                {
                    b.HasOne("DAL.Models.PERSONA", "Persona")
                        .WithOne("CLIENTE")
                        .HasForeignKey("DAL.Models.CLIENTE", "ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__CLIENTE__ID_Clie__440B1D61");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DAL.Models.CONTRATO", b =>
                {
                    b.HasOne("DAL.Models.CLIENTE", "ID_ClienteNavigation")
                        .WithMany("CONTRATOS")
                        .HasForeignKey("ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__CONTRATO__ID_Cli__52593CB8");

                    b.Navigation("ID_ClienteNavigation");
                });

            modelBuilder.Entity("DAL.Models.DETECTIVE", b =>
                {
                    b.HasOne("DAL.Models.PERSONA", "Persona")
                        .WithOne("DETECTIVE")
                        .HasForeignKey("DAL.Models.DETECTIVE", "ID_Detective")
                        .IsRequired()
                        .HasConstraintName("FK__DETECTIVE__ID_De__412EB0B6");

                    b.Navigation("Persona");
                });

            modelBuilder.Entity("DAL.Models.EVIDENCIA", b =>
                {
                    b.HasOne("DAL.Models.CASO", "ID_CasosNavigation")
                        .WithMany("EVIDENCIAS")
                        .HasForeignKey("ID_Casos")
                        .IsRequired()
                        .HasConstraintName("FK__EVIDENCIA__ID_Ca__5AEE82B9");

                    b.Navigation("ID_CasosNavigation");
                });

            modelBuilder.Entity("DAL.Models.FACTURA", b =>
                {
                    b.HasOne("DAL.Models.CLIENTE", "ID_ClienteNavigation")
                        .WithMany("FACTURAS")
                        .HasForeignKey("ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__FACTURA__ID_Clie__4F7CD00D");

                    b.Navigation("ID_ClienteNavigation");
                });

            modelBuilder.Entity("DAL.Models.FORMULARIO", b =>
                {
                    b.HasOne("DAL.Models.CLIENTE", "ID_ClienteNavigation")
                        .WithMany("FORMULARIOS")
                        .HasForeignKey("ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__FORMULARI__ID_Cl__49C3F6B7");

                    b.Navigation("ID_ClienteNavigation");
                });

            modelBuilder.Entity("DAL.Models.HISTORIAL", b =>
                {
                    b.HasOne("DAL.Models.CLIENTE", "ID_ClienteNavigation")
                        .WithMany("HISTORIALES")
                        .HasForeignKey("ID_Cliente")
                        .IsRequired()
                        .HasConstraintName("FK__HISTORIAL__ID_Cl__4CA06362");

                    b.Navigation("ID_ClienteNavigation");
                });

            modelBuilder.Entity("DAL.Models.REGISTRO_CASO", b =>
                {
                    b.HasOne("DAL.Models.CASO", "ID_CasosNavigation")
                        .WithMany("REGISTRO_CASOS")
                        .HasForeignKey("ID_Casos")
                        .IsRequired()
                        .HasConstraintName("FK__REGISTRO___ID_Ca__5812160E");

                    b.Navigation("ID_CasosNavigation");
                });

            modelBuilder.Entity("DAL.Models.REGISTRO_MANTENIMIENTO", b =>
                {
                    b.HasOne("DAL.Models.ADMINISTRADOR", "ID_AdministradorNavigation")
                        .WithMany("REGISTRO_MANTENIMIENTOS")
                        .HasForeignKey("ID_Administrador")
                        .IsRequired()
                        .HasConstraintName("FK__REGISTRO___ID_Ad__46E78A0C");

                    b.Navigation("ID_AdministradorNavigation");
                });

            modelBuilder.Entity("DAL.Models.TIPO_EVIDENCIA", b =>
                {
                    b.HasOne("DAL.Models.EVIDENCIA", "ID_EvidenciaNavigation")
                        .WithMany("TIPO_EVIDENCIAS")
                        .HasForeignKey("ID_Evidencia")
                        .IsRequired()
                        .HasConstraintName("FK__TIPO_EVID__ID_Ev__628FA481");

                    b.Navigation("ID_EvidenciaNavigation");
                });

            modelBuilder.Entity("DAL.Models.USUARIO", b =>
                {
                    b.HasOne("DAL.Models.ROLE", "Rol")
                        .WithMany("USUARIOS")
                        .HasForeignKey("RolId")
                        .IsRequired()
                        .HasConstraintName("FK__USUARIO__RolId__3B75D760");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("DAL.Models.ADMINISTRADOR", b =>
                {
                    b.Navigation("REGISTRO_MANTENIMIENTOS");
                });

            modelBuilder.Entity("DAL.Models.CASO", b =>
                {
                    b.Navigation("EVIDENCIAS");

                    b.Navigation("REGISTRO_CASOS");
                });

            modelBuilder.Entity("DAL.Models.CLIENTE", b =>
                {
                    b.Navigation("CASOS");

                    b.Navigation("CONTRATOS");

                    b.Navigation("FACTURAS");

                    b.Navigation("FORMULARIOS");

                    b.Navigation("HISTORIALES");
                });

            modelBuilder.Entity("DAL.Models.EVIDENCIA", b =>
                {
                    b.Navigation("TIPO_EVIDENCIAS");
                });

            modelBuilder.Entity("DAL.Models.PERSONA", b =>
                {
                    b.Navigation("ADMINISTRADOR");

                    b.Navigation("CLIENTE");

                    b.Navigation("DETECTIVE");
                });

            modelBuilder.Entity("DAL.Models.ROLE", b =>
                {
                    b.Navigation("USUARIOS");
                });

            modelBuilder.Entity("DAL.Models.USUARIO", b =>
                {
                    b.Navigation("AUDITORIAS");
                });
#pragma warning restore 612, 618
        }
    }
}
